### ISSUE TITLE
Missing items from spawn menu

### ISSUE THREAD

**Issue by DryTaste** [Acher0ns/Umbra-Mod-Menu#18]
Things like the scrapper and chests are missing from the spawn menu since the last update, being able to spawn scrappers was pretty convenient

1. Inject menu
2. Open menu ingame
3. Spawn: On
4. Spawn List: On
5. Observe items missing from list

**Comment by Acher0ns** [comment]
In the future, create a separate issue for the feature request

**Comment by Acher0ns** [comment]
Also note: This has been a bug since spawn menu was added. ATM the spawn list changes depending on when the menu is injected.

**Comment by Acher0ns** [comment]
Fixed in rewrite branch.
