### ISSUE TITLE
Items Menu, Buff Menu, Equiptment Menu Blank, Unlock All doesn't unlock all

### ISSUE THREAD

**Issue by 1131616305** [Acher0ns/Umbra-Mod-Menu#24]
Get all items is not available

**Comment by Acher0ns** [comment]
Items Menu, Buff Menu, Equiptment Menu Blank, Unlock All doesn't unlock all

It has come to my understanding that Hoopo has somewhat entirely removed the ItemIndex enum, so it is likely many of these dont work

**Comment by 1131616305** [comment]
There should be other ways to get it

**Comment by Acher0ns** [comment]
There are, I just don't have the time to implement them right now but it probably includes an Items Class they added or the ItemCatalog class
