### ISSUE TITLE
Keeps finding..?

### ISSUE THREAD

**Issue by FixerWixer** [Acher0ns/Umbra-Mod-Menu#25]
It keeps saying finding for risk of rain 2 but never injects? this has never happened before i think it was the new update that caused this

**Comment by Snow-Developer** [comment]
Is this with the injector or are you using a separate injector?

**Comment by FixerWixer** [comment]
with the injector

**Comment by Snow-Developer** [comment]
I unfortunately do not have much experience with the injector, are you sure you have the latest version?

**Comment by Acher0ns** [comment]
Try to make sure your game is running/in the main menu when you inject. Also make sure you're using the latest version of the injector and umbra menu.
