### ISSUE TITLE
Crashes the game after the update

### ISSUE THREAD

**Issue by lauwalker** [Acher0ns/Umbra-Mod-Menu#26]
The injector instantly crashes the game upon injection. This is probably due to the recent update, and the injector may need an update.

**Comment by Snow-Developer** [comment]
Working on it.

**Comment by lauwalker** [comment]
Tried injecting v2.0.2 on the base game with no DLC enabled, and the base game continues to crash.

**Comment by Snow-Developer** [comment]
> Tried injecting v2.0.2 on the base game with no DLC enabled, and the base game continues to crash. Edit: Now bought the DLC and tested it, and v2.0.2 on injector v1.0.2 also leads to a crash.

This will be fixed after the pull request is pushed to the master branch.
